Feat/browser package
appbaseio/dejaVu pull request #359
Opened 2019-11-29 13:16 UTC by ShahAnuj2610

2019-12-02 12:03 UTC, ShahAnuj2610 commented
dependent on: https://github.com/appbaseio/batteries/pull/173

2020-01-02 09:31 UTC, lakhansamani commented on packages/browser/package.json
>  		"codesandbox": "1.3.5",
I don't think we need `codesandbox` or any packages related to Search Preview here, they should be part of `dejavu-main`.

You can try removing packages listed here and not used by `browser`
https://github.com/appbaseio/batteries

2020-01-02 09:33 UTC, lakhansamani requested changes
Remove battiers dependencies which are not required by `dejavu-browser`

2020-01-07 06:38 UTC, lakhansamani commented
@ShahAnuj2610 can you share build command + dist repositories that need to be set here?

2020-01-07 06:58 UTC, lakhansamani requested changes

2020-01-07 06:58 UTC, lakhansamani commented on packages/browser/package.json
> +	"name": "dejavu-data-browser",
@ShahAnuj2610 can you change this to `@appbaseio/dejavu-browser`

2020-01-07 06:58 UTC, lakhansamani commented on .eslintrc.js
> +  parser: 'babel-eslint',
Can you fix your editor config and use tab size as per editor config.

2020-01-07 06:58 UTC, lakhansamani commented on package.json
> +		"build:dejavu:site": "yarn build:browser && lerna run build:site --scope dejavu-main --stream"
Can you add code formating using `prettier`

https://github.com/appbaseio/dejavu/blob/dev/package.json#L23

Also, chrome extension build is missing
https://github.com/appbaseio/dejavu/blob/dev/package.json#L24

Make sure extension & its build works correctly

2020-01-07 06:58 UTC, lakhansamani commented on packages/browser/src/components/ConnectApp/ConnectApp.js
> +		const { mode, isConnected, isHidden, forceReconnect } = this.props;
Can you add a comment on when `foreceReconnect` is required?

2020-01-07 06:59 UTC, lakhansamani commented
@ShahAnuj2610 can you bring docker file at the root
https://github.com/ShahAnuj2610/dejavu/blob/feat/browser-package/packages/dejavu-main/Dockerfile

And make changes for the folder structure there

2020-01-07 07:01 UTC, lakhansamani commented
@ShahAnuj2610 there is one css bug
When you navigate to `search preview` and come back to `browser screen` 

observe horizontal scroll

![](https://www.dropbox.com/s/lr3fa1vz0fdttiv/Screenshot%202020-01-07%2012.18.57.png?raw=1)

2020-01-07 07:04 UTC, lakhansamani commented on packages/dejavu-main/app/src/components/OldDejavuBanner/OldDejavuBanner.js
> +	console.log('hello');
Please remove log

2020-01-07 11:05 UTC, ShahAnuj2610 commented
@lakhansamani have done the changes. Here are some command line instructions

### How to publish to npm?

from the root of the project run the following command
```
yarn && yarn build:browser && cd packages/browser && npm publish
```

### How to run locally with watchers?

from the root of the project run the following command
```
yarn && yarn dev:browser && yarn dev:dejavu
```

### netlify config

![](https://i.imgur.com/gZ2S58v.png)

2020-01-23 14:51 UTC, merged